**Library Imports**

In [ ]:
import sys
import numpy as np
from numpy.linalg import inv
from fractions import Fraction

**Feeding the Matrix A (Coefficients) and B**

In [ ]:
mat = np.matrix('1 -1 -1 -1 -1 0 0 0 0 0 0 0; 0 1 0 0 0 0 0 0 -1 -1 -1 0; 0 0 0 1 0 0 1 0 0 0 1 -1; 0 0 0 0 1 -1 -1 -1 0 0 0 0; 1 0 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 1 0 0 -5 0 0 0 0; 0 0 0 1 0 0 1 0 0 0 0 -0.84; 0.7 -1 -1 0 0 0 0 0 0 0 0 0; 0.55 0 0 0 0 0 0 0 -1 0 0 -1; 0 0 0 0 0 0 0 0 0.2 -1 0 0; 0 0.85 0 0 0 0 0 0 -1 0 -1 0; 0 0 0 0 0 3.2 -1 -1 0 0 0 0')
mat_b = np.matrix('0; 0; 0; 0; 100; 0; 0; 0; 0; 0; 0; 0')
print("Matrix A\n")
print(mat)
print("\nMatrix B\n")
print(mat_b)

Matrix A

[[ 1.   -1.   -1.   -1.   -1.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.    0.    0.    0.   -1.   -1.   -1.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    1.    0.    0.    0.    1.   -1.  ]
 [ 0.    0.    0.    0.    1.   -1.   -1.   -1.    0.    0.    0.    0.  ]
 [ 1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    1.    0.    0.   -5.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    1.    0.    0.    0.    0.   -0.84]
 [ 0.7  -1.   -1.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.55  0.    0.    0.    0.    0.    0.    0.   -1.    0.    0.   -1.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.2  -1.    0.    0.  ]
 [ 0.    0.85  0.    0.    0.    0.    0.    0.   -1.    0.   -1.    0.  ]
 [ 0.    0.    0.    0.    0.    3.2  -1.   -1.    0.    0.    0.    0.  ]]

Matrix B

[[  0]
 [  0]
 [  0]
 [  0]
 [100]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 

**Matrix Inversion Method**

In [ ]:
mat_inv = inv(mat)
ans = mat_inv*mat_b
ans

matrix([[100.        ],
        [ 40.        ],
        [ 30.        ],
        [  9.45652174],
        [ 20.54347826],
        [  4.89130435],
        [ 11.54347826],
        [  4.10869565],
        [ 30.        ],
        [  6.        ],
        [  4.        ],
        [ 25.        ]])

**Creating Augmented Matrix**

In [ ]:
# Making numpy array of n x n+1 size and initializing to zero for storing augmented matrix
a = np.zeros((n,n+1))

# Making numpy array of n size and initializing to zero for storing solution vector
x = np.zeros(n)

# Augmented matrix coefficients
for i in range(n):
    for j in range(n):
        a[i][j] = ma[i][j]
for i in range(n):
  j = n
  a[i][j] = mat_b[i]

**Function for Gauss Elimination Method**

In [ ]:
def pprint(A):
    n = len(A)
    for i in range(0, n):
        line = ""
        for j in range(0, n + 1):
            line += str(A[i][j]) + "\t"
            if j == n - 1:
                line += "| "
        print(line)
    print("")


def gauss(A):
    n = len(A)

    for i in range(0, n):
        # Search for maximum in this column
        maxEl = abs(A[i][i])
        maxRow = i
        for k in range(i + 1, n):
            if abs(A[k][i]) > maxEl:
                maxEl = abs(A[k][i])
                maxRow = k

        # Swap maximum row with current row (column by column)
        for k in range(i, n + 1):
            tmp = A[maxRow][k]
            A[maxRow][k] = A[i][k]
            A[i][k] = tmp

        # Make all rows below this one 0 in current column
        for k in range(i + 1, n):
            c = -A[k][i] / A[i][i]
            for j in range(i, n + 1):
                if i == j:
                    A[k][j] = 0
                else:
                    A[k][j] += c * A[i][j]

    # Solve equation Ax=b for an upper triangular matrix A
    x = [0 for i in range(n)]
    for i in range(n - 1, -1, -1):
        x[i] = A[i][n] / A[i][i]
        for k in range(i - 1, -1, -1):
            A[k][n] -= A[k][i] * x[i]
    return x


if __name__ == "__main__":

    n = 12
    # Augmented Matrix A
    A = a

    # Print input
    pprint(A)

    # Calculate solution
    x = gauss(A)

    # Print result
    line = "Result:\t"
    for i in range(0, n):
        line += str(x[i]) + "\t"
    print(line)

1.0	-1.0	-1.0	-1.0	-1.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	| 0.0	
0.0	1.0	0.0	0.0	0.0	0.0	0.0	0.0	-1.0	-1.0	-1.0	0.0	| 0.0	
0.0	0.0	0.0	1.0	0.0	0.0	1.0	0.0	0.0	0.0	1.0	-1.0	| 0.0	
0.0	0.0	0.0	0.0	1.0	-1.0	-1.0	-1.0	0.0	0.0	0.0	0.0	| 0.0	
0.0	0.0	1.0	1.0	1.0	0.0	0.0	0.0	1.0	1.0	1.0	0.0	| 100.0	
0.0	0.0	0.0	0.0	1.0	0.0	0.0	-5.0	0.0	0.0	0.0	0.0	| 0.0	
0.0	0.0	0.0	1.0	0.0	0.0	1.0	0.0	0.0	0.0	0.0	-0.84	| 0.0	
0.0	0.0	-0.30000000000000004	0.7	0.7	0.0	0.0	0.0	-0.30000000000000004	-0.30000000000000004	-0.30000000000000004	0.0	| 0.0	
0.0	0.0	0.55	0.55	0.55	0.0	0.0	0.0	-0.44999999999999996	0.55	0.55	-1.0	| 0.0	
0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.2	-1.0	0.0	0.0	| 0.0	
0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	-0.15000000000000002	0.85	-0.15000000000000002	0.0	| 0.0	
0.0	0.0	0.0	0.0	0.0	3.2	-1.0	-1.0	0.0	0.0	0.0	0.0	| 0.0	

Result:	100.0	40.000000000000014	29.999999999999986	9.456521739130416	20.543478260869584	4.891304347826091	11.543478260869577	4.1086956521739175	30.000000000000014	6.000000000000003	3.9999999999